name: Build and Deploy ASP.NET Core and Blazor Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0' 

      - name: Build Backend (ASP.NET Core)
        run: |
          cd RustDetector.api
          dotnet build --configuration Release

      - name: Publish Backend (ASP.NET Core)
        run: |
          cd RustDetector.api
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for backend deployment
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      - name: Download Backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-artifact

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rustdetector'
          slot-name: 'Production'
          package: ./RustDetector.api/bin/Release/net8.0/publish 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D3196DCE27274553A3C438185ECE00E7 }}
          
      - name: Checkout repository again
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for Frontend (Blazor Web App)
        run: |
          cd RustDetector.blazor
          npm install

      - name: Build Frontend (Blazor Web App)
        run: |
          cd RustDetector.blazor
          dotnet build

      - name: Publish Frontend (Blazor Web App)
        run: |
          cd RustDetector.blazor
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/blazorapp

      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rustdetector'
          slot-name: 'Production'
          package: ./RustDetector.blazor/bin/Release/net8.0/publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D3196DCE27274553A3C438185ECE00E7 }}
