name: Rust Detector Scraper

on:
  schedule:
    - cron: '0 12 28-31 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if it is the last day of the month
      run: |
        if [ $(date +\%d -d tomorrow) -eq 1 ]; then
          python rust-detector.py
        else
          echo "Not the last day of the month. Maybe tomorrow..."
        fi
